"""候補rendererの疎・標準・上限・長文入力を目視確認する回帰データ。"""


REVIEW_DECK = {
    "meta": {
        "title": "候補renderer汎用性レビュー",
        "footer": "候補renderer汎用性レビュー",
        "date": "2026年8月",
        "organization": "業務改善推進部",
        "author": "テンプレート整備担当",
    },
    "slides": [
        {
            "type": "scope", "kicker": "対象範囲 / 疎",
            "title": "初回リリースで扱う範囲を、最小限の項目で合意する",
            "in_scope": ["申請受付と承認状況の参照"],
            "out_of_scope": ["既存ワークフローの全面更改"],
        },
        {
            "type": "scope", "kicker": "対象範囲 / 標準",
            "title": "移行プロジェクトの実施範囲と責任境界を明確にする",
            "in_scope": [
                "対象業務の要件整理と新しい運用フローの設計",
                "既存システムとのインターフェース設計・実装",
                "本番移行と初期運用期間の問い合わせ対応",
                "利用部門向けの操作説明と運用手順の整備",
            ],
            "out_of_scope": [
                "端末・ネットワーク機器の調達と設置",
                "今回の対象外となる周辺システムの機能改修",
                "初期運用期間終了後の長期保守業務",
            ],
            "assumptions": ["データを所定形式で受領", "関係部門のレビュー担当を確保"],
        },
        {
            "type": "scope", "kicker": "対象範囲 / 上限",
            "title": "複数部門が関わる更改で、作業範囲・対象外・成立条件を漏れなく確認する",
            "lead": "各項目を6件まで増やしても、左右の読み順と前提条件の優先度を維持します。",
            "in_scope": [
                "業務要件・非機能要件・移行要件の整理と合意形成",
                "アプリケーション、API、バッチ処理の設計と実装",
                "既存データの抽出・変換・移行リハーサルと本番移行",
                "総合試験、受入試験、性能試験に必要な環境の整備",
                "監視・バックアップ・障害対応を含む運用設計",
                "利用部門向け教育、運用引継ぎ、初期安定化支援",
            ],
            "out_of_scope": [
                "利用部門が個別に管理する端末と周辺機器の更新",
                "接続先システム側で必要となる業務機能の追加開発",
                "法令・制度改正に伴う将来要件への継続的な追随",
                "本番稼働後の定常保守と24時間365日の監視運用",
                "移行元データの名寄せ・欠損補完・品質改善作業",
                "対象外拠点の回線更改とネットワーク機器の再配置",
            ],
            "assumptions": [
                "意思決定者が隔週でレビューに参加", "接続仕様を設計開始前に受領",
                "試験データを所定品質で準備", "移行期間中も既存基盤が安定稼働",
            ],
        },
        {
            "type": "summary", "kicker": "意思決定要約 / 疎",
            "title": "現状と判断だけを短く示し、次の会議で決めることを揃える",
            "sections": [
                {"heading": "現状", "body": "個別運用が増え、確認作業に時間を要している。"},
                {"heading": "判断", "body": "共通化できる業務から段階的に標準手順へ移行する。"},
            ],
        },
        {
            "type": "summary", "kicker": "意思決定要約 / 標準",
            "title": "背景・判断・提案を整理し、意思決定を1枚で支援する",
            "sections": [
                {"heading": "背景", "body": "部門ごとに資料の構成と確認方法が異なり、作成とレビューの双方に手戻りが発生している。"},
                {"heading": "判断", "body": "全資料を一律化せず、頻出する業務パターンから提出品質を標準化する方が導入負荷を抑えられる。"},
                {"heading": "提案", "body": "対象部門で標準レイアウトを試行し、品質・作成時間・運用負荷を測定して展開可否を判断する。"},
            ],
            "conclusion": "限定導入で効果と運用条件を確認した後、対象業務を段階的に拡大する。",
        },
        {
            "type": "summary", "kicker": "意思決定要約 / 上限",
            "title": "4つの判断材料を整理し、実行可否と条件を役員会へ提示する",
            "lead": "各論点は事実と示唆を分け、最後に判断文を1文で固定します。",
            "sections": [
                {"heading": "市場環境", "body": "競合各社はセルフサービス化を進め、問い合わせから回答までの時間を短縮している。"},
                {"heading": "顧客影響", "body": "現行の受付方法では繁忙期の待ち時間が増え、解約意向の高い顧客を早期に把握できない。"},
                {"heading": "実現性", "body": "既存CRMと認証基盤を活用できるため、対象業務を限定すれば6か月以内に提供開始できる。"},
                {"heading": "主要リスク", "body": "回答品質と権限管理を担保するため、公開前レビューと利用ログ監査を運用へ組み込む必要がある。"},
            ],
            "conclusion": "対象顧客と回答範囲を限定した実証を開始し、品質基準を満たした段階で全社展開を判断する。",
        },
        {
            "type": "paired_comparison", "kicker": "方式比較 / 疎",
            "title": "短期導入と長期運用の違いを、2つの評価軸だけで確認する",
            "left_label": "個別対応", "right_label": "標準化",
            "rows": [
                {"criterion": "導入速度", "left": "既存手順を維持してすぐ開始できる", "right": "初期設計と共通部品の整備が必要"},
                {"criterion": "運用負荷", "left": "対象拡大に比例して確認作業が増える", "right": "再利用により追加対応を抑えられる"},
            ],
        },
        {
            "type": "paired_comparison", "kicker": "方式比較 / 標準",
            "title": "現行方式と標準方式を、同じ評価軸で比較する",
            "left_label": "現行方式", "right_label": "標準方式",
            "rows": [
                {"criterion": "運用負荷", "left": "担当者ごとの個別対応が多い", "right": "共通手順により確認作業を削減"},
                {"criterion": "導入速度", "left": "初期設定は少なく短期導入しやすい", "right": "初期整備後は再利用によって展開を加速"},
                {"criterion": "柔軟性", "left": "個別要望へ即時に対応できる", "right": "共通部品と例外ルールを組み合わせる"},
                {"criterion": "品質", "left": "担当者の経験により差が生じる", "right": "標準検証により品質と一貫性を維持"},
                {"criterion": "拡張性", "left": "対象拡大に比例して運用負荷が増える", "right": "共通基盤を再利用して対象を追加できる"},
            ],
            "takeaway": "短期の立ち上げは現行方式、中長期の横展開は標準方式が優位となる。",
        },
        {
            "type": "paired_comparison", "kicker": "方式比較 / 上限",
            "title": "6つの観点で移行方式を比較し、採用条件と残課題を明確にする",
            "lead": "評価軸と左右の説明が長い場合も、対応する行を見失わないことを確認します。",
            "left_label": "一括移行", "right_label": "段階移行",
            "rows": [
                {"criterion": "停止時間", "left": "全機能を同日に切り替えるため長時間停止が必要", "right": "対象単位で切り替え、停止影響を局所化できる"},
                {"criterion": "移行期間", "left": "準備完了後は短期間で旧環境を廃止できる", "right": "並行運用が続くため全体完了まで時間を要する"},
                {"criterion": "障害影響", "left": "問題発生時に全利用部門へ影響が及ぶ", "right": "先行対象で問題を検出し、後続へ反映できる"},
                {"criterion": "データ整合", "left": "切替時点を揃えやすく二重管理を避けられる", "right": "移行期間中の同期方式と更新ルールが必要"},
                {"criterion": "要員負荷", "left": "短期間に多くの担当者と支援要員を集中配置する", "right": "長期間の体制維持が必要だがピーク負荷を抑えられる"},
                {"criterion": "切戻し", "left": "全体を戻す手順と判断時間の確保が難しい", "right": "対象単位で切り戻し、影響範囲を限定できる"},
            ],
            "takeaway": "業務停止を最小化するため段階移行を採用し、同期運用の負荷を計画へ織り込む。",
        },
        {
            "type": "mapping", "kicker": "対応関係 / 疎",
            "title": "2つの要件と機能を対応させ、実装漏れを確認する",
            "left_label": "要件", "right_label": "機能",
            "left_items": [{"id": "auth", "text": "社外から安全に利用できる"}, {"id": "audit", "text": "操作履歴を追跡できる"}],
            "right_items": [{"id": "mfa", "text": "多要素認証"}, {"id": "log", "text": "監査ログ保管"}],
            "links": [{"from": "auth", "to": "mfa", "emphasis": True}, {"from": "audit", "to": "log"}],
        },
        {
            "type": "mapping", "kicker": "対応関係 / 標準",
            "title": "主要課題と施策をひも付け、対応漏れを確認する",
            "left_label": "主要課題", "right_label": "対応施策",
            "left_items": [
                {"id": "manual", "text": "手作業が多く処理時間が長い"}, {"id": "data", "text": "データが複数の管理先へ分散"},
                {"id": "approval", "text": "承認完了までの待ち時間が長い"}, {"id": "quality", "text": "成果物の品質にばらつき"},
                {"id": "visibility", "text": "進捗と課題の把握に時間がかかる"},
            ],
            "right_items": [
                {"id": "standardize", "text": "定型作業の標準化と自動化"}, {"id": "integrate", "text": "データ管理先の統合"},
                {"id": "rules", "text": "承認条件と判断権限の見直し"}, {"id": "review", "text": "レビュー基準と品質ゲート"},
                {"id": "dashboard", "text": "進捗・課題ダッシュボード"},
            ],
            "links": [
                {"from": "manual", "to": "standardize", "emphasis": True}, {"from": "data", "to": "integrate"},
                {"from": "data", "to": "dashboard"}, {"from": "approval", "to": "rules"},
                {"from": "quality", "to": "review"}, {"from": "visibility", "to": "dashboard"},
            ],
        },
        {
            "type": "mapping", "kicker": "対応関係 / 上限",
            "title": "要件と施策が多対多でも、接続順を最適化して対応漏れを確認する",
            "lead": "6項目・10対応まで増やし、複数施策が同じ要件へ寄与する関係を検証します。",
            "left_label": "重点要件", "right_label": "実施施策",
            "left_items": [
                {"id": "speed", "text": "申請から回答までの時間を半減"}, {"id": "quality", "text": "回答品質を部門横断で統一"},
                {"id": "audit", "text": "判断根拠と操作履歴を追跡"}, {"id": "resilience", "text": "障害時も重要業務を継続"},
                {"id": "cost", "text": "運用費を3年間で20%削減"}, {"id": "growth", "text": "利用部門追加へ迅速に対応"},
            ],
            "right_items": [
                {"id": "workflow", "text": "申請・承認フローの標準化"}, {"id": "knowledge", "text": "ナレッジと回答基準の共通化"},
                {"id": "logging", "text": "監査ログと証跡管理の強化"}, {"id": "dr", "text": "冗長化と復旧手順の整備"},
                {"id": "automation", "text": "定型確認の自動化"}, {"id": "platform", "text": "共通基盤と再利用部品の整備"},
            ],
            "links": [
                {"from": "speed", "to": "workflow", "emphasis": True}, {"from": "speed", "to": "automation"},
                {"from": "quality", "to": "knowledge"}, {"from": "quality", "to": "workflow"},
                {"from": "audit", "to": "logging"}, {"from": "resilience", "to": "dr"},
                {"from": "cost", "to": "automation"}, {"from": "cost", "to": "platform"},
                {"from": "growth", "to": "platform"}, {"from": "growth", "to": "knowledge"},
            ],
        },
        {
            "type": "swimlane", "kicker": "担当フロー / 疎",
            "title": "依頼から完了連絡までの受け渡しを、2部門で確認する",
            "lanes": [{"id": "requester", "label": "依頼部門"}, {"id": "operator", "label": "運用担当"}],
            "stages": [{"id": "request", "label": "依頼"}, {"id": "complete", "label": "対応・完了"}],
            "steps": [
                {"id": "submit", "name": "依頼登録", "lane": "requester", "stage": "request"},
                {"id": "execute", "name": "対応実施", "lane": "operator", "stage": "complete", "style": "accent"},
                {"id": "accept", "name": "完了確認", "lane": "requester", "stage": "complete"},
            ],
            "edges": [{"from": "submit", "to": "execute"}, {"from": "execute", "to": "accept"}],
        },
        {
            "type": "swimlane", "kicker": "担当フロー / 標準",
            "title": "障害対応の担当境界と引き継ぎ点を明確にする",
            "lanes": [{"id": "user", "label": "利用部門"}, {"id": "ops", "label": "運用担当"}, {"id": "network", "label": "ネットワーク担当"}, {"id": "carrier", "label": "回線事業者"}],
            "stages": [{"id": "detect", "label": "検知・申告"}, {"id": "verify", "label": "確認・切り分け"}, {"id": "recover", "label": "対応・復旧"}, {"id": "close", "label": "確認・完了"}],
            "steps": [
                {"id": "report", "name": "障害申告", "lane": "user", "stage": "detect"}, {"id": "triage", "name": "一次確認", "lane": "ops", "stage": "verify"},
                {"id": "monitor", "name": "監視確認", "lane": "ops", "stage": "verify"}, {"id": "device", "name": "機器確認", "lane": "network", "stage": "verify"},
                {"id": "escalate", "name": "エスカレーション", "lane": "ops", "stage": "recover"}, {"id": "isolate", "name": "回線切り分け", "lane": "network", "stage": "recover"},
                {"id": "provider", "name": "回線調査・復旧", "lane": "carrier", "stage": "recover", "style": "accent"}, {"id": "result", "name": "結果確認", "lane": "ops", "stage": "recover"},
                {"id": "notify", "name": "利用者連絡", "lane": "user", "stage": "close"}, {"id": "close", "name": "クローズ", "lane": "user", "stage": "close"},
            ],
            "edges": [
                {"from": "report", "to": "triage"}, {"from": "triage", "to": "monitor"}, {"from": "triage", "to": "device"},
                {"from": "monitor", "to": "escalate"}, {"from": "device", "to": "isolate"}, {"from": "escalate", "to": "isolate"},
                {"from": "isolate", "to": "provider"}, {"from": "provider", "to": "result"}, {"from": "result", "to": "notify"}, {"from": "notify", "to": "close"},
            ],
        },
        {
            "type": "swimlane", "kicker": "担当フロー / 上限",
            "title": "6部門・6段階の審査フローで、分岐・引き継ぎ・差戻しを確認する",
            "lead": "14工程と前段階への差戻しを含む上限構成で、配線と文字縮小を検証します。",
            "lanes": [{"id": "sales", "label": "営業"}, {"id": "office", "label": "事務局"}, {"id": "security", "label": "セキュリティ"}, {"id": "legal", "label": "法務"}, {"id": "finance", "label": "経理"}, {"id": "approver", "label": "決裁者"}],
            "stages": [{"id": "draft", "label": "起案"}, {"id": "check", "label": "形式確認"}, {"id": "review", "label": "専門審査"}, {"id": "adjust", "label": "条件調整"}, {"id": "approve", "label": "決裁"}, {"id": "close", "label": "完了"}],
            "steps": [
                {"id": "draft", "name": "申請起案", "lane": "sales", "stage": "draft"}, {"id": "register", "name": "受付登録", "lane": "office", "stage": "check"},
                {"id": "format", "name": "形式確認", "lane": "office", "stage": "check"}, {"id": "risk", "name": "リスク評価", "lane": "security", "stage": "review"},
                {"id": "contract", "name": "契約審査", "lane": "legal", "stage": "review"}, {"id": "budget", "name": "予算確認", "lane": "finance", "stage": "review"},
                {"id": "security_fix", "name": "対策条件整理", "lane": "security", "stage": "adjust"}, {"id": "terms", "name": "契約条件調整", "lane": "legal", "stage": "adjust"},
                {"id": "cost", "name": "費用条件確定", "lane": "finance", "stage": "adjust"}, {"id": "compile", "name": "審査結果集約", "lane": "office", "stage": "approve"},
                {"id": "decision", "name": "決裁", "lane": "approver", "stage": "approve", "style": "accent"}, {"id": "revise", "name": "申請修正", "lane": "sales", "stage": "adjust"},
                {"id": "notify", "name": "結果通知", "lane": "office", "stage": "close"}, {"id": "archive", "name": "証跡保管", "lane": "office", "stage": "close"},
            ],
            "edges": [
                {"from": "draft", "to": "register"}, {"from": "register", "to": "format"}, {"from": "format", "to": "risk"}, {"from": "format", "to": "contract"},
                {"from": "format", "to": "budget"}, {"from": "risk", "to": "security_fix"}, {"from": "contract", "to": "terms"}, {"from": "budget", "to": "cost"},
                {"from": "security_fix", "to": "compile"}, {"from": "terms", "to": "compile"}, {"from": "cost", "to": "compile"}, {"from": "compile", "to": "decision"},
                {"from": "decision", "to": "notify"}, {"from": "notify", "to": "archive"}, {"from": "decision", "to": "revise", "kind": "feedback"}, {"from": "revise", "to": "compile"},
            ],
        },
        {
            "type": "sequence", "kicker": "実行順序 / 疎",
            "title": "利用者とサービス間の認証処理を、最小構成で確認する",
            "participants": [{"id": "user", "label": "利用者"}, {"id": "service", "label": "業務サービス"}],
            "messages": [
                {"id": "request", "from": "user", "to": "service", "label": "ログイン要求"},
                {"id": "verify", "from": "service", "to": "service", "label": "資格情報を検証"},
                {"id": "result", "from": "service", "to": "user", "label": "認証結果", "kind": "return"},
            ],
        },
        {
            "type": "sequence", "kicker": "実行順序 / 標準",
            "title": "関係者・機器・確認ポイントを、実行順に整理する",
            "participants": [{"id": "ops", "label": "運用担当"}, {"id": "monitor", "label": "監視システム"}, {"id": "branch", "label": "拠点ルータ"}, {"id": "center", "label": "センタールータ"}, {"id": "carrier", "label": "回線事業者"}],
            "messages": [
                {"id": "detect", "from": "monitor", "to": "ops", "label": "障害検知", "kind": "async"}, {"id": "request", "from": "ops", "to": "branch", "label": "確認依頼"},
                {"id": "reply", "from": "branch", "to": "ops", "label": "疎通結果", "kind": "return"}, {"id": "logs", "from": "monitor", "to": "branch", "label": "ログ確認"},
                {"id": "isolate", "from": "branch", "to": "center", "label": "区間切り分け"}, {"id": "carrier", "from": "center", "to": "carrier", "label": "回線確認"},
                {"id": "recover", "from": "carrier", "to": "center", "label": "復旧連絡", "kind": "return"}, {"id": "report", "from": "monitor", "to": "ops", "label": "正常性確認"},
            ],
            "phases": [{"label": "調査", "from": "request", "to": "carrier"}, {"label": "復旧", "from": "recover", "to": "report"}],
        },
        {
            "type": "sequence", "kicker": "実行順序 / 上限",
            "title": "6つの関係者が参加するリリース手順を、12メッセージと3フェーズで確認する",
            "lead": "自己処理・非同期通知・応答を含む上限構成で、ラベルとライフラインの判読性を検証します。",
            "participants": [{"id": "owner", "label": "変更責任者"}, {"id": "operator", "label": "作業担当"}, {"id": "pipeline", "label": "配備基盤"}, {"id": "app", "label": "業務サービス"}, {"id": "monitor", "label": "監視基盤"}, {"id": "desk", "label": "利用部門窓口"}],
            "messages": [
                {"id": "approve", "from": "owner", "to": "operator", "label": "実施承認"}, {"id": "prepare", "from": "operator", "to": "operator", "label": "手順と対象を再確認"},
                {"id": "deploy", "from": "operator", "to": "pipeline", "label": "配備開始"}, {"id": "apply", "from": "pipeline", "to": "app", "label": "変更を適用"},
                {"id": "complete", "from": "app", "to": "pipeline", "label": "適用結果", "kind": "return"}, {"id": "notify", "from": "pipeline", "to": "monitor", "label": "監視強化を通知", "kind": "async"},
                {"id": "health", "from": "monitor", "to": "app", "label": "正常性確認"}, {"id": "status", "from": "app", "to": "monitor", "label": "稼働状態", "kind": "return"},
                {"id": "accept", "from": "operator", "to": "desk", "label": "利用確認を依頼"}, {"id": "answer", "from": "desk", "to": "operator", "label": "確認完了", "kind": "return"},
                {"id": "report", "from": "operator", "to": "owner", "label": "実施結果を報告"}, {"id": "close", "from": "owner", "to": "operator", "label": "作業完了を承認", "kind": "return"},
            ],
            "phases": [{"label": "準備", "from": "approve", "to": "prepare"}, {"label": "実施", "from": "deploy", "to": "notify"}, {"label": "確認", "from": "health", "to": "close"}],
        },
        {
            "type": "scope", "kicker": "対象範囲 / 長文",
            "title": "長い作業名称でも、対象・対象外・前提条件の境界を読み違えない",
            "in_scope": [
                "全社共通の申請受付から部門責任者による承認結果通知までの業務プロセス設計",
                "既存の顧客管理基盤および認証基盤との接続仕様策定と結合試験",
                "本番移行後1か月間の問い合わせ一次対応と運用担当者への引継ぎ",
            ],
            "out_of_scope": [
                "利用部門が独自運用する表計算ファイルの内容整理とデータ品質改善",
                "接続先システム側で将来予定されている機能追加への継続的な追随",
                "初期安定化期間終了後の定常保守および夜間休日の監視運用",
            ],
            "assumptions": [
                "接続仕様書を基本設計開始前に受領", "意思決定者が隔週レビューへ参加",
                "移行対象データを所定品質で準備",
            ],
        },
        {
            "type": "summary", "kicker": "意思決定要約 / 長文",
            "title": "文章量が増えても、論点と結論の優先順位を崩さず提示する",
            "sections": [
                {
                    "heading": "検討背景",
                    "body": "問い合わせ件数の増加に対して担当者の増員だけで対応しており、繁忙期には回答遅延と引継ぎ漏れが同時に発生している。現行運用を維持したまま対象部門を増やすことは難しい。",
                },
                {
                    "heading": "推奨判断",
                    "body": "受付分類と定型回答を共通化し、判断が必要な案件だけを専門担当へ引き継ぐ。まず限定部門で品質と処理時間を測定し、基準を満たした場合に対象を段階的に拡大する。",
                },
            ],
            "conclusion": "限定導入で回答品質と運用負荷を検証し、改善効果を確認した後に全社展開を判断する。",
        },
        {
            "type": "paired_comparison", "kicker": "方式比較 / 長文",
            "title": "説明が長い比較でも、評価軸ごとの対応関係を崩さず判断材料を示す",
            "left_label": "現行環境を延命", "right_label": "共通基盤へ段階移行",
            "rows": [
                {
                    "criterion": "初期対応",
                    "left": "既存構成を維持するため短期間で開始できるが、老朽部品の調達と個別設定の継続が必要となる",
                    "right": "共通部品と移行手順の初期整備が必要だが、後続部門では設計と試験を再利用できる",
                },
                {
                    "criterion": "障害影響",
                    "left": "障害原因と復旧手順が環境ごとに異なり、担当者の経験によって復旧時間に差が生じる",
                    "right": "監視項目と復旧手順を標準化し、先行部門で得た知見を後続部門へ反映できる",
                },
                {
                    "criterion": "運用費用",
                    "left": "初期投資は抑えられる一方、個別保守と更改対応が残り、中長期の要員負荷が増加する",
                    "right": "移行期間中は二重運用が必要だが、完了後は共通運用により保守費用を抑制できる",
                },
            ],
            "takeaway": "短期費用だけでなく、障害対応と保守要員を含む3年間の総負荷で移行方式を判断する。",
        },
        {
            "type": "mapping", "kicker": "対応関係 / 長文",
            "title": "長い要件・施策名称でも、対応先を直接たどって照合する",
            "left_label": "業務・統制要件", "right_label": "実装・運用施策",
            "left_items": [
                {"id": "speed", "text": "申請受付から一次回答までの所要時間を繁忙期でも2営業日以内に維持"},
                {"id": "quality", "text": "担当部門が異なっても回答内容と判断根拠の品質を一定水準に統一"},
                {"id": "audit", "text": "承認判断と回答修正の履歴を監査時に案件単位で追跡可能にする"},
                {"id": "continuity", "text": "一部機能の障害時にも優先度の高い問い合わせ受付を継続"},
            ],
            "right_items": [
                {"id": "classify", "text": "受付内容の自動分類と優先度に応じた担当振り分け"},
                {"id": "knowledge", "text": "承認済み回答と判断基準を管理する共通ナレッジ基盤"},
                {"id": "logging", "text": "操作ログ・承認履歴・回答版数を統合する証跡管理"},
                {"id": "fallback", "text": "障害時の代替受付と手動運用へ切り替える継続手順"},
            ],
            "links": [
                {"from": "speed", "to": "classify", "emphasis": True},
                {"from": "speed", "to": "knowledge"},
                {"from": "quality", "to": "knowledge"},
                {"from": "quality", "to": "logging"},
                {"from": "audit", "to": "logging"},
                {"from": "continuity", "to": "fallback"},
                {"from": "continuity", "to": "classify"},
            ],
        },
        {
            "type": "swimlane", "kicker": "担当フロー / 長文",
            "title": "担当名と工程名が長い場合も、引き継ぎ経路と実施主体を判別する",
            "lanes": [
                {"id": "requester", "label": "申請元部門責任者"},
                {"id": "office", "label": "全社受付・審査事務局"},
                {"id": "security", "label": "情報セキュリティ管理部門"},
                {"id": "approver", "label": "最終決裁権限者"},
            ],
            "stages": [
                {"id": "request", "label": "申請内容の登録"},
                {"id": "check", "label": "形式・不足確認"},
                {"id": "review", "label": "リスク評価・条件調整"},
                {"id": "decision", "label": "決裁・結果通知"},
            ],
            "steps": [
                {"id": "submit", "name": "申請書と証跡を登録", "lane": "requester", "stage": "request"},
                {"id": "format", "name": "必須項目と添付資料を確認", "lane": "office", "stage": "check"},
                {"id": "risk", "name": "情報資産と接続先のリスクを評価", "lane": "security", "stage": "review"},
                {"id": "adjust", "name": "実施条件と残存リスクを整理", "lane": "office", "stage": "review"},
                {"id": "approve", "name": "条件付き実施可否を決裁", "lane": "approver", "stage": "decision", "style": "accent"},
                {"id": "notify", "name": "審査結果と実施条件を通知", "lane": "office", "stage": "decision"},
            ],
            "edges": [
                {"from": "submit", "to": "format"}, {"from": "format", "to": "risk"},
                {"from": "risk", "to": "adjust"}, {"from": "adjust", "to": "approve"},
                {"from": "approve", "to": "notify"},
            ],
        },
        {
            "type": "sequence", "kicker": "実行順序 / 長文",
            "title": "参加者名とメッセージが長い場合も、送信元・送信先・応答順を追跡する",
            "participants": [
                {"id": "requester", "label": "利用部門の申請責任者"},
                {"id": "portal", "label": "統合申請ポータル"},
                {"id": "workflow", "label": "承認ワークフロー基盤"},
                {"id": "auditor", "label": "証跡・監査ログ管理基盤"},
            ],
            "messages": [
                {"id": "submit", "from": "requester", "to": "portal", "label": "申請内容と必要証跡を登録"},
                {"id": "validate", "from": "portal", "to": "portal", "label": "入力形式と必須項目を自動検証"},
                {"id": "request", "from": "portal", "to": "workflow", "label": "承認依頼と判断期限を通知", "kind": "async"},
                {"id": "record", "from": "workflow", "to": "auditor", "label": "承認判断と根拠情報を記録"},
                {"id": "complete", "from": "workflow", "to": "portal", "label": "承認結果と実施条件を返却", "kind": "return"},
                {"id": "notify", "from": "portal", "to": "requester", "label": "審査結果と次の対応を通知", "kind": "return"},
            ],
            "phases": [
                {"label": "受付・確認", "from": "submit", "to": "validate"},
                {"label": "承認・記録", "from": "request", "to": "record"},
                {"label": "結果通知", "from": "complete", "to": "notify"},
            ],
        },
    ],
}
