"""社内テンプレートのパターン検証用デッキ定義。"""

from copy import deepcopy

from diagram_specs import AWS_MULTIAZ_EXAMPLE, AWS_SIMPLE_EXAMPLE

PATTERN_DECK = {
    "meta": {
        "title": "社内スライドパターン検証ギャラリー",
        "footer": "社内スライドパターン検証ギャラリー",
        "date": "2026年7月",
        "organization": "業務企画本部\n業務改善推進部",
        "author": "業務改善検討チーム",
    },
    "slides": [
        {
            "type": "title",
            "title": "社内スライド\nパターンライブラリ",
            "subtitle": "意思決定から技術研修まで、24のTypeを34枚で検証",
        },
        {
            "type": "bullets",
            "style": "numbered",
            "kicker": "検討手順",
            "title": "意思決定資料は、論点を3段階で組み立てる",
            "bullets": [
                {"text": "判断したい論点を1文で定義し、読み手と目的を揃える"},
                {"text": "事実と制約を整理し、選択肢ごとの違いを比較する"},
                {"text": "推奨案と実施条件を示し、次の判断につなげる"},
            ],
        },
        {
            "type": "bullets",
            "style": "bullet",
            "kicker": "判断材料",
            "title": "移行判断では、費用・影響・運用条件を揃える",
            "bullets": [
                {"text": "初期費用と継続費用を分け、比較期間を統一する"},
                {"text": "利用部門・既存業務・周辺システムへの影響を確認する"},
                {"text": "移行中の停止時間と、切り戻し条件を明確にする"},
                {"text": "運用開始後の責任分界と問い合わせ窓口を決める"},
            ],
        },
        {
            "type": "bullets",
            "style": "checklist",
            "kicker": "実施準備",
            "title": "リリース前に、残タスクと完了条件を確認する",
            "bullets": [
                {"text": "本番手順と切り戻し手順のレビュー", "checked": True},
                {"text": "関係部門への実施日時と影響範囲の連絡", "checked": True},
                {"text": "監視項目・通知先・初動担当の最終確認", "checked": False},
                {"text": "リリース判定会議での承認取得", "checked": False},
            ],
        },
        {
            "type": "cards",
            "style": "editorial",
            "kicker": "結論と根拠",
            "title": "全社展開の推奨案と、効果・実現性・導入リスクを示す",
            "cards": [
                {"heading": "推奨案", "body": "標準テンプレートを対象部門へ段階展開する。",
                 "emphasis": True},
                {"heading": "期待効果", "body": "作成とレビューの手戻りを減らし、提出品質を揃える。"},
                {"heading": "実現性", "body": "既存フローを流用し、部門ごとに順次導入できる。"},
                {"heading": "導入リスク", "body": "初期教育と運用窓口を用意し、例外資料は個別対応とする。"},
            ],
        },
        {
            "type": "cards",
            "style": "metrics",
            "kicker": "KPIスナップショット",
            "title": "KPIは数値を主役にし、判断材料を添える",
            "cards": [
                {"heading": "作成時間", "value": "-72%",
                 "body": "週次報告の作成時間が平均45分から13分に短縮。下書き作成の自動化が主因。",
                 "emphasis": True},
                {"heading": "手直し", "value": "8分",
                 "body": "生成後の確認と語尾修正に平均8分。テンプレート崩れは検出なし。"},
                {"heading": "再利用率", "value": "64%",
                 "body": "一度作った構造化データを翌週も流用でき、定型資料ほど効果が高い。"},
            ],
        },
        {
            "type": "two_column",
            "kicker": "Before / After",
            "title": "導入前後の違いを、同じ観点で比較する",
            "left": {
                "label": "現状",
                "heading": "導入前",
                "bullets": [
                    "担当者ごとにスライド構成がばらつき、レビュー観点も揃わない",
                    "グラフや表の貼り付け後に、余白・フォント・禁則を手作業で直す",
                    "過去資料をコピーして使うため、古い文言や注記が残りやすい",
                ],
            },
            "right": {
                "label": "目標状態",
                "heading": "導入後",
                "bullets": [
                    "入力schemaに沿って文言を作るため、構成の揺れを抑えられる",
                    "rendererが余白・フォント・描画順を決め、提出前の確認に集中できる",
                    "品質ゲートで重なりやはみ出しを検知し、修正箇所を特定しやすい",
                ],
            },
        },
        {
            "type": "table",
            "kicker": "方式比較",
            "title": "選定理由と見送り理由を、同じ粒度で比較する",
            "columns": ["方式", "向いている用途", "強み", "注意点"],
            "rows": [
                ["renderer カタログ", "社内標準資料・定型報告", "品質を詰めた型を再利用できる", "新しい型は実装が必要"],
                ["万能宣言レイアウト", "図の大量バリエーション", "座標指定を減らせる", "エンジンが複雑化しやすい"],
                ["手作業PPT", "一点物の重要提案", "細部まで作り込める", "再現性と量産性が低い"],
            ],
        },
        {
            "type": "chart",
            "kicker": "効果測定",
            "title": "資料作成時間を最大72%短縮",
            "note": "値は検証用のサンプルデータ。",
            "chart": {
                "categories": ["週次報告", "月次レビュー", "調査サマリ", "役員向け抜粋"],
                "series": [
                    ["従来 (分)", [45, 120, 240, 90]],
                    ["生成後 (分)", [13, 42, 85, 28]],
                ],
            },
        },
        {
            "type": "chart",
            "kicker": "利用推移",
            "title": "月次利用率は、試行開始から継続的に上昇",
            "chart": {
                "kind": "line",
                "categories": ["4月", "5月", "6月", "7月", "8月", "9月",
                               "10月", "11月", "12月"],
                "series": [
                    ["利用率", [12, 18, 25, 31, 44, 52, 61, 67, 74]],
                    ["目標", [20, 25, 30, 35, 40, 50, 60, 70, 80]],
                ],
                "show_values": False,
            },
            "note": "値は検証用のサンプルデータ。",
        },
        {
            "type": "chart",
            "kicker": "工数内訳",
            "title": "自動化後は、作成よりレビューへ時間を配分できる",
            "chart": {
                "kind": "stacked_column",
                "categories": ["導入前", "試行中", "標準化後"],
                "series": [
                    ["作成", [70, 38, 18]],
                    ["レビュー", [20, 32, 42]],
                    ["意思決定", [10, 30, 40]],
                ],
                "number_format": "0\"%\"",
            },
            "note": "構成比を示すサンプル。",
        },
        {
            "type": "image",
            "kicker": "画面イメージ",
            "title": "画面キャプチャを、スライドの主役として大きく見せる",
            "image": "images/pptxdsl-repository.png",
            "fit": "cover",
            "shadow": True,
            "alt": "GitHubで公開されているpptxdslリポジトリのトップ画面",
        },
        {
            "type": "image_compare",
            "kicker": "画面比較",
            "title": "変更前後のスクリーンショットを左右で比較する",
            "left": {
                "image": "images/pptxdsl-repository.png",
                "label": "変更前",
                "alt": "GitHubで公開されているpptxdslリポジトリのトップ画面",
            },
            "right": {
                "image": "cover/cover-background.png",
                "label": "変更後",
                "alt": "濃紺のグラデーションに幾何学的な線を重ねた背景素材",
            },
            "fit": "cover",
            "shadow": True,
        },
        {
            "type": "process",
            "kicker": "標準プロセス",
            "title": "資料生成は5つの工程で品質を担保する",
            "steps": [
                {"name": "入力整理", "desc": "目的・読み手・必須メッセージを整理する。",
                 "attribute": {"label": "INPUT", "value": "資料要件"}},
                {"name": "構造化", "desc": "schemaに沿ってスライド種別と文言を作る。",
                 "attribute": {"label": "METHOD", "value": "schema"}},
                {"name": "生成", "desc": "rendererがPPTXを決定論的に出力する。",
                 "attribute": {"label": "OUTPUT", "value": "PPTX"}},
                {"name": "検証", "desc": "機械検知と目視で崩れを確認する。",
                 "attribute": {"label": "CHECK", "value": "機械 + 目視"}},
                {"name": "提出", "desc": "contentを直して再生成し、提出する。",
                 "attribute": {"label": "STATE", "value": "提出可能"}},
            ],
            "emph": [3],
        },
        {
            "type": "process",
            "kicker": "承認フロー",
            "title": "通常の承認経路と差戻しを、迷わず追える形で示す",
            "flow": {
                "nodes": {
                    "request": {"name": "申請", "desc": "必要事項を登録", "actor": "申請部門"},
                    "check": {"name": "形式確認", "desc": "不足項目を確認", "actor": "事務局"},
                    "review": {"name": "内容審査", "desc": "妥当性とリスクを確認", "actor": "審査部門",
                               "style": "decision"},
                    "revise": {"name": "修正", "desc": "指摘事項を反映", "actor": "申請部門"},
                    "execute": {"name": "実施", "desc": "承認内容に沿って着手", "actor": "実施部門",
                                "style": "accent"},
                },
                "levels": [
                    ["request"], ["check"], ["review"],
                    ["execute", "revise"],
                ],
                "edges": [
                    {"from": "request", "to": "check"},
                    {"from": "check", "to": "review"},
                    {"from": "review", "to": "execute", "label": "承認"},
                    {"from": "review", "to": "revise", "label": "要修正"},
                    {"from": "revise", "to": "check", "kind": "feedback",
                     "label": "再申請"},
                ],
            },
        },
        {
            "type": "program_roadmap",
            "kicker": "展開計画",
            "title": "12か月で型の整備から全社標準へ移行する",
            "periods": ["4月", "5月", "6月", "7月", "8月", "9月",
                        "10月", "11月", "12月", "1月", "2月", "3月"],
            "tracks": [
                {"name": "型の定義", "goal": "主要パターンを選定",
                 "activities": [{"label": "標準レイアウトを定義",
                                  "start": "4月", "end": "5月"}],
                 "milestone": {"at": "5月", "label": "型レビュー"}},
                {"name": "実装", "goal": "rendererを整備",
                 "activities": [{"label": "生成・検証機能を実装",
                                  "start": "5月", "end": "7月"}]},
                {"name": "現場検証", "goal": "複数部門で試行",
                 "activities": [{"label": "パイロット運用",
                                  "start": "7月", "end": "10月"}],
                 "milestone": {"at": "10月", "label": "展開判断"}},
                {"name": "改善", "goal": "利用結果を反映",
                 "activities": [{"label": "品質・操作性を改善",
                                  "start": "10月", "end": "12月"}]},
                {"name": "標準化", "goal": "全社手順へ組込",
                 "activities": [{"label": "標準運用へ移行",
                                  "start": "1月", "end": "3月"}],
                 "milestone": {"at": "3月", "label": "標準化"}},
            ],
        },
        {
            "type": "program_roadmap",
            "kicker": "年間プログラム",
            "title": "5つの改善テーマと並行作業を、年間計画として俯瞰する",
            "periods": ["4月", "5月", "6月", "7月", "8月", "9月",
                        "10月", "11月", "12月", "1月", "2月", "3月"],
            "tracks": [
                {
                    "name": "利用部門の拡大",
                    "activities": [
                        {"label": "対象業務の選定", "start": 0.25, "end": 2.75},
                        {"label": "追加部門へ展開", "start": 7.5, "end": 12,
                         "emph": True},
                    ],
                },
                {
                    "name": "デザイン標準化",
                    "activities": [
                        {"label": "利用要件の整理", "start": "4月", "end": "6月"},
                        {"label": "共通仕様の策定", "start": "6月", "end": "9月"},
                        {"label": "試行版の検証", "start": "7月", "end": "10月"},
                    ],
                },
                {
                    "name": "運用基盤の再設計",
                    "activities": [
                        {"label": "現状調査", "start": "4月", "end": "5月"},
                        {"label": "移行方針の策定", "start": "6月", "end": "9月"},
                        {"label": "新環境の構築", "start": "7月", "end": "10月"},
                        {"label": "運用リハーサル", "start": "8月", "end": "8月"},
                        {"label": "本番移行", "start": "9月", "end": "10月", "emph": True},
                        {"label": "旧環境の停止", "start": "12月", "end": "3月"},
                    ],
                },
                {
                    "name": "外部サービス連携",
                    "activities": [
                        {"label": "方式検討", "start": "5月", "end": "6月"},
                        {"label": "接続開発", "start": "7月", "end": "9月"},
                        {"label": "段階展開", "start": "10月", "end": "10月"},
                    ],
                },
                {
                    "name": "データ活用基盤",
                    "activities": [
                        {"label": "要件定義", "start": "5月", "end": "6月"},
                        {"label": "基盤構築", "start": "6月", "end": "9月"},
                        {"label": "利用検証", "start": "10月", "end": "11月"},
                        {"label": "全社展開", "start": "12月", "end": "2月", "emph": True},
                    ],
                },
            ],
            "note": "月途中の開始・終了は1/4月単位で表現する。",
        },
        {
            "type": "matrix",
            "kicker": "優先度整理",
            "title": "提出品質と再利用性から、整備優先度を決める",
            "x_axis": "再利用性 →",
            "y_axis": "↑ 提出品質",
            "target_label": "優先整備",
            "quadrants": ["個別対応", "再利用候補", "品質改善", "優先整備"],
            "points": [
                {"name": "タイトル", "x": 0.18, "y": 0.58},
                {"name": "要点列", "x": 0.72, "y": 0.76, "emph": True},
                {"name": "比較表", "x": 0.68, "y": 0.66},
                {"name": "ロードマップ", "x": 0.44, "y": 0.62},
                {"name": "高密度構成図", "x": 0.35, "y": 0.86},
                {"name": "自由配置図", "x": 0.20, "y": 0.32},
            ],
            "note": "位置づけはテンプレート整備の優先度を示すサンプル。",
        },
        {
            "type": "org",
            "kicker": "推進体制",
            "title": "責任者から各チームまで、指揮系統を明確にする",
            "org": {
                "nodes": {
                    "project_owner": {
                        "name": "プロジェクト責任者", "sub": "方針・予算を決定",
                        "style": "primary"},
                    "system_owner": {
                        "name": "システム責任者", "sub": "システム方針を決定",
                        "style": "primary"},
                    "project_manager": {
                        "name": "プロジェクトマネージャー", "sub": "計画・課題・品質を統括",
                        "style": "accent"},
                    "business_team": {
                        "name": "業務チーム", "sub": "業務要件・受入を担当"},
                    "application_team": {
                        "name": "開発チーム", "sub": "設計・開発・試験を担当"},
                    "platform_team": {
                        "name": "基盤チーム", "sub": "基盤・ネットワークを担当"},
                    "operation_team": {
                        "name": "移行・運用チーム", "sub": "移行・運用設計を担当"},
                },
                "levels": [
                    ["project_owner", "system_owner"],
                    ["project_manager"],
                    ["business_team", "application_team", "platform_team",
                     "operation_team"],
                ],
                "edges": [
                    {"from": "project_owner", "to": "project_manager"},
                    {"from": "system_owner", "to": "project_manager"},
                    {"from": "project_manager", "to": "business_team"},
                    {"from": "project_manager", "to": "application_team"},
                    {"from": "project_manager", "to": "platform_team"},
                    {"from": "project_manager", "to": "operation_team"},
                ],
            },
        },
        {
            "type": "diagram",
            "diagram": deepcopy(AWS_SIMPLE_EXAMPLE),
            "kicker": "構成図",
            "title": "主要コンポーネントとデータの流れを短く示す",
            "note": "AWSアイコンは slidegen/assets/icons/aws/ から読み込む。",
        },
        {
            "type": "diagram",
            "diagram": deepcopy(AWS_MULTIAZ_EXAMPLE),
            "kicker": "高密度構成図",
            "title": "高密度なAWS構成も、グリッド仕様で自動配置する",
        },
        {
            # AWS以外の構成図も、同梱Fluentアイコンを指定して描けることを検証する。
            "type": "diagram",
            "kicker": "Fluentアイコン構成図",
            "title": "SSO・監査・バックアップを含む業務システム構成を表現する",
            "note": "同梱のMicrosoft Fluent UIアイコンを使用。ライセンスはslidegen/assets/CREDITS.mdを参照。",
            "diagram": {
                "cols": ["user", "edge", "app", "data"],
                "rows": ["top", "main", "bottom"],
                "nodes": {
                    "client": {"col": "user", "row": "main",
                                "icon": "icons/fluent/desktop.png",
                                "title": "利用者端末", "sub": "社内LAN"},
                    "identity": {"col": "app", "row": "top",
                                 "icon": "icons/fluent/key.png",
                                 "title": "ID基盤"},
                    "fw": {"col": "edge", "row": "main",
                           "icon": "icons/fluent/shield.png",
                           "title": "ファイアウォール"},
                    "web": {"col": "app", "row": "main",
                            "icon": "icons/fluent/server.png",
                            "title": "業務Webサーバ", "sub": "アプリ本体"},
                    "db": {"col": "data", "row": "main",
                           "icon": "icons/fluent/database.png", "title": "DBサーバ"},
                    "log": {"col": "app", "row": "bottom",
                             "icon": "icons/fluent/monitor.png",
                             "title": "ログ収集", "sub": "監査用"},
                    "backup": {"col": "data", "row": "bottom",
                               "icon": "icons/fluent/storage.png",
                               "title": "バックアップ", "sub": "日次保管"},
                },
                "containers": [
                    {"name": "dc", "label": "データセンター",
                     "members": ["fw", "web", "db", "log", "backup"]},
                ],
                "channels": {
                    "identity_lane": ["right_of_col", "app"],
                    "log_lane": ["left_of_col", "app"],
                    "backup_lane": ["outside_container", ["dc", "right"]],
                },
                "edges": [
                    {"from": "client", "to": "fw", "label": "HTTPS"},
                    {"from": "fw", "to": "web"},
                    {"from": "identity", "to": "web",
                     "label": "認証"},
                    {"from": "web", "to": "db", "label": "SQL"},
                    {"from": "web", "to": "log", "exit": "bottom",
                     "enter": "left", "via": ["log_lane"],
                     "label": "監査ログ", "dash": "dash"},
                    {"from": "db", "to": "backup", "exit": "right",
                     "enter": "right", "via": ["backup_lane"],
                     "label": "日次", "dash": "dash"},
                ],
            },
        },
        {
            "type": "diagram",
            "kicker": "イベント駆動構成図",
            "title": "受付と処理を分離し、保存・監視へ非同期分岐する",
            "diagram": {
                "cols": ["client", "api", "queue", "worker", "data"],
                "rows": ["top", "main", "bottom"],
                "nodes": {
                    "client": {"col": "client", "row": "main",
                               "icon": "icons/aws/users.png", "title": "業務システム",
                               "sub": "イベント送信元"},
                    "api": {"col": "api", "row": "main",
                            "icon": "icons/fluent/globe.png",
                            "title": "受付API", "sub": "検証・受付"},
                    "queue": {"col": "queue", "row": "main",
                              "icon": "icons/aws/sqs.png", "title": "Amazon SQS",
                              "sub": "処理待ちキュー"},
                    "worker": {"col": "worker", "row": "main",
                               "icon": "icons/fluent/server.png",
                               "title": "非同期ワーカー", "sub": "変換・集計"},
                    "state": {"col": "data", "row": "top",
                              "icon": "icons/aws/dynamodb.png", "title": "DynamoDB",
                              "sub": "処理状態"},
                    "artifact": {"col": "data", "row": "bottom",
                                 "icon": "icons/aws/s3.png", "title": "Amazon S3",
                                 "sub": "成果物"},
                    "monitor": {"col": "worker", "row": "bottom",
                                "icon": "icons/aws/cloudwatch.png", "title": "CloudWatch",
                                "sub": "監視・ログ"},
                },
                "containers": [
                    {"name": "cloud", "label": "AWS Cloud",
                     "members": ["@async", "state", "artifact"]},
                    {"name": "async", "label": "Asynchronous Processing",
                     "members": ["api", "queue", "worker", "monitor"],
                     "color": "navy"},
                ],
                "channels": {},
                "edges": [
                    {"from": "client", "to": "api", "label": "HTTPS"},
                    {"from": "api", "to": "queue", "label": "受付"},
                    {"from": "queue", "to": "worker", "label": "非同期"},
                    {"from": "worker", "to": "state", "label": "状態更新"},
                    {"from": "worker", "to": "artifact", "label": "成果物"},
                    {"from": "worker", "to": "monitor", "dash": "dash"},
                ],
            },
        },
        {
            "type": "concept",
            "kicker": "言葉の定義",
            "title": "RTOは、障害発生から業務再開までの目標時間を表す",
            "term": "RTO",
            "definition": "Recovery Time Objectiveの略です。障害が起きてから、業務やサービスを再開するまでに許容する目標時間を定めます。",
            "icon": "icons/fluent/clock.png",
            "points": [
                {"label": "起点", "text": "業務やサービスへ影響する障害が発生した時点。"},
                {"label": "終点", "text": "利用者が必要な業務を再開できる状態へ戻った時点。"},
                {"label": "設計への反映", "text": "復旧手順、冗長化、バックアップ方式の要求へ落とし込む。"},
            ],
            "misconception": "実際に要した復旧時間の実績値ではなく、事前に合意する目標値です。",
        },
        {
            "type": "nw_topology",
            "kicker": "ネットワーク構成",
            "title": "物理リンクを共有しながら、用途別の通信範囲を分離する",
            "lanes": [
                {"id": "business", "label": "業務VLAN", "sub": "社内端末"},
                {"id": "guest", "label": "ゲストVLAN", "sub": "来訪者端末"},
            ],
            "columns": [
                {"id": "left", "label": "フロアA"},
                {"id": "switch_a", "label": "スイッチA"},
                {"id": "switch_b", "label": "スイッチB"},
                {"id": "right", "label": "フロアB"},
            ],
            "nodes": [
                {"id": "staff_a", "label": "業務PC A", "icon": "icons/fluent/laptop.png", "column": "left", "lanes": ["business"]},
                {"id": "guest_a", "label": "ゲスト端末 A", "icon": "icons/fluent/phone.png", "column": "left", "lanes": ["guest"]},
                {"id": "switch_a", "label": "スイッチA", "icon": "icons/fluent/switch.png", "column": "switch_a", "lanes": ["business", "guest"]},
                {"id": "switch_b", "label": "スイッチB", "icon": "icons/fluent/switch.png", "column": "switch_b", "lanes": ["business", "guest"]},
                {"id": "staff_b", "label": "業務PC B", "icon": "icons/fluent/desktop.png", "column": "right", "lanes": ["business"]},
                {"id": "guest_b", "label": "ゲスト端末 B", "icon": "icons/fluent/phone.png", "column": "right", "lanes": ["guest"]},
            ],
            "links": [
                {"from": "staff_a", "to": "switch_a", "kind": "access", "lanes": ["business"]},
                {"from": "guest_a", "to": "switch_a", "kind": "access", "lanes": ["guest"]},
                {"from": "switch_a", "to": "switch_b", "kind": "trunk", "lanes": ["business", "guest"], "label": "Trunk"},
                {"from": "switch_b", "to": "staff_b", "kind": "access", "lanes": ["business"]},
                {"from": "switch_b", "to": "guest_b", "kind": "access", "lanes": ["guest"]},
            ],
        },
        {
            "type": "nw_protocol_flow",
            "kicker": "IPパケット状態の追跡",
            "title": "NAT前後の送信元IPを、処理段階ごとに追跡する",
            "lead": "NATでは送信元IPを書き換え、宛先IPは維持したまま外部へ転送する。",
            "stages": [
                {"id": "client", "label": "社内端末", "icon": "icons/fluent/laptop.png", "role": "endpoint"},
                {"id": "inside", "label": "ルーター内側", "icon": "icons/fluent/ethernet.png", "role": "processor"},
                {"id": "nat", "label": "NAT処理", "icon": "icons/fluent/switch.png", "role": "processor"},
                {"id": "internet", "label": "インターネット区間", "icon": "icons/fluent/link.png", "role": "link"},
                {"id": "server", "label": "外部サーバー", "icon": "icons/fluent/server.png", "role": "endpoint"},
            ],
            "flows": [
                {
                    "label": "送信元IP",
                    "sub": "アドレス変換",
                    "states": [
                        {"stage": "client", "label": "10.0.0.25", "detail": "端末のプライベートIP", "appearance": "plain"},
                        {"stage": "inside", "label": "10.0.0.25", "detail": "変換前の送信元", "appearance": "plain"},
                        {"stage": "nat", "label": "203.0.113.10", "detail": "送信元を書き換え", "appearance": "internal"},
                        {"stage": "internet", "label": "203.0.113.10", "detail": "変換後のパケット", "appearance": "plain"},
                        {"stage": "server", "label": "203.0.113.10", "detail": "外部から見える送信元", "appearance": "plain"},
                    ],
                },
                {
                    "label": "宛先IP",
                    "sub": "変化なし",
                    "states": [
                        {"stage": "client", "label": "198.51.100.20", "detail": "外部サーバー", "appearance": "plain"},
                        {"stage": "inside", "label": "198.51.100.20", "detail": "宛先を維持", "appearance": "plain"},
                        {"stage": "nat", "label": "198.51.100.20", "detail": "宛先を維持", "appearance": "internal"},
                        {"stage": "internet", "label": "198.51.100.20", "detail": "外部へ転送", "appearance": "plain"},
                        {"stage": "server", "label": "198.51.100.20", "detail": "自分宛てとして受信", "appearance": "plain"},
                    ],
                },
            ],
        },
        {
            "type": "nw_frame_anatomy",
            "kicker": "プロトコル構造",
            "title": "TCPセグメントを分解し、制御情報とデータの位置を読む",
            "lead": "フィールドを位置で捉え、パケットキャプチャの値を役割へ結び付ける。",
            "frames": [
                {
                    "label": "TCP",
                    "fields": [
                        {"id": "src", "name": "送信元Port", "bits": 16},
                        {"id": "dst", "name": "宛先Port", "bits": 16},
                        {"id": "seq", "name": "Sequence", "bits": 32, "role": "highlight"},
                        {"id": "ack", "name": "ACK", "bits": 32, "role": "highlight"},
                        {"id": "flags", "name": "Flags", "bits": 9, "role": "alert"},
                        {"id": "window", "name": "Window", "bits": 16},
                        {"id": "payload", "name": "Payload", "bits": 512, "role": "muted"},
                    ],
                    "annotations": [
                        {"field": "seq", "text": "受信側が並び順と欠落を判断する番号。"},
                        {"field": "ack", "text": "次に受信したい位置を相手へ通知する。"},
                        {"field": "flags", "text": "接続開始・終了などの状態を示す。"},
                    ],
                }
            ],
        },
        {
            "type": "config_lab",
            "kicker": "設定と確認",
            "title": "設定例と確認コマンドを並べ、変更後の状態まで検証する",
            "lead": "コマンドの実行ではなく、期待状態の確認までを作業単位とする。",
            "sections": [
                {"label": "設定例", "code": "service:\n  image: example/app:2.4\n  replicas: 3\n  healthcheck:\n    path: /health"},
                {"label": "確認コマンド", "code": "deploy --file service.yml\nstatus service\nlogs service --tail 50"},
            ],
            "check_label": "確認する状態",
            "checks": [
                "稼働数が指定したreplicasと一致している",
                "healthcheckが成功し、トラフィックを受けられる",
                "直近ログに起動失敗や設定エラーがない",
                "切り戻し用の直前バージョンを特定できる",
            ],
        },
        {
            "type": "knowledge_check",
            "mode": "questions",
            "kicker": "理解度チェック",
            "title": "判断理由を選び、運用設計の理解を確認する",
            "questions": [
                {"question": "監視通知を設計するとき、最初に決めるものはどれか。", "options": ["検知したい利用者影響", "通知メールの色", "担当者の座席"], "answer": 0, "explanation": "利用者影響から必要な検知条件と通知先を逆算します。"},
                {"question": "変更後の確認として最も適切なものはどれか。", "options": ["コマンドが終了したこと", "期待状態と実測値の一致", "手順書のページ数"], "answer": 1, "explanation": "実行結果ではなく、期待したサービス状態になったことを確認します。"},
                {"question": "例外対応を残すときに必要な情報はどれか。", "options": ["適用条件と承認者", "作成者の好み", "画面の配色"], "answer": 0, "explanation": "例外の適用条件、期限、承認責任を追跡可能にします。"},
            ],
        },
        {
            "type": "scope_boundary",
            "kicker": "対象範囲",
            "title": "実施範囲と対象外を分け、責任境界を明確にする",
            "lead": "必要なデータ、関係部門のレビュー体制、既存基盤の安定稼働を着手条件とする。",
            "in_label": "実施範囲",
            "out_label": "対象外",
            "in_scope": [
                "対象業務の要件整理と新しい運用フローの設計",
                "既存システムとのインターフェース設計・実装",
                "本番移行と初期運用期間の問い合わせ対応",
                "利用部門向けの操作説明と運用手順の整備",
            ],
            "out_of_scope": [
                "端末・ネットワーク機器の調達と設置",
                "今回の対象外となる周辺システムの機能改修",
                "初期運用期間終了後の長期保守業務",
                "移行元データの名寄せと内容補正",
            ],
        },
        {
            "type": "decision_summary",
            "kicker": "経営判断",
            "title": "背景・判断・提案を整理し、意思決定を1枚で支援する",
            "lead": "限定導入で効果と運用条件を確認した後、対象業務を段階的に拡大する。",
            "sections": [
                {
                    "heading": "背景",
                    "icon": "info",
                    "body": "部門ごとに資料の構成と確認方法が異なり、作成とレビューの双方に手戻りが発生している。",
                },
                {
                    "heading": "判断",
                    "icon": "check",
                    "body": "全資料を一律化するのではなく、頻出する業務パターンから標準化する方が導入負荷を抑えられる。",
                },
                {
                    "heading": "提案",
                    "icon": "send",
                    "body": "対象部門で標準レイアウトを試行し、品質・作成時間・運用負荷を測定して展開可否を判断する。",
                },
            ],
        },
        {
            "type": "paired_comparison",
            "kicker": "方式比較",
            "title": "現行方式と標準方式を、同じ評価軸で比較する",
            "lead": "短期の立ち上げは現行方式、中長期の横展開は標準方式が優位となる。",
            "left_label": "現行方式",
            "right_label": "標準方式",
            "rows": [
                {"criterion": "運用負荷", "left": "担当者ごとの個別対応が多い",
                 "right": "共通手順により確認作業を削減"},
                {"criterion": "導入速度", "left": "初期設定は少なく短期導入しやすい",
                 "right": "初期整備後は再利用によって展開を加速"},
                {"criterion": "柔軟性", "left": "個別要望へ即時に対応できる",
                 "right": "共通部品と例外ルールを組み合わせる"},
                {"criterion": "品質", "left": "担当者の経験により差が生じる",
                 "right": "標準検証により品質と一貫性を維持"},
                {"criterion": "拡張性", "left": "対象拡大に比例して運用負荷が増える",
                 "right": "共通基盤を再利用して対象を追加できる"},
            ],
        },
        {
            "type": "relationship_map",
            "kicker": "対応関係",
            "title": "主要課題と施策をひも付け、対応漏れを確認する",
            "left_label": "主要課題",
            "right_label": "対応施策",
            "left_items": [
                {"id": "manual", "text": "手作業が多く処理時間が長い"},
                {"id": "data", "text": "データが複数の管理先へ分散している"},
                {"id": "approval", "text": "承認完了までの待ち時間が長い"},
                {"id": "quality", "text": "成果物の品質にばらつきがある"},
                {"id": "visibility", "text": "進捗と課題の把握に時間がかかる"},
            ],
            "right_items": [
                {"id": "standardize", "text": "定型作業の標準化と自動化"},
                {"id": "integrate", "text": "データ管理先の統合"},
                {"id": "rules", "text": "承認条件と判断権限の見直し"},
                {"id": "review", "text": "レビュー基準と品質ゲートの整備"},
                {"id": "dashboard", "text": "進捗・課題ダッシュボードの整備"},
            ],
            "links": [
                {"from": "manual", "to": "standardize", "emphasis": True},
                {"from": "data", "to": "integrate"},
                {"from": "data", "to": "dashboard"},
                {"from": "approval", "to": "rules"},
                {"from": "quality", "to": "review"},
                {"from": "visibility", "to": "dashboard"},
            ],
        },
        {
            "type": "swimlane_flow",
            "kicker": "障害対応フロー",
            "title": "障害対応スイムレーン",
            "lead": "担当境界と引き継ぎ点を明示し、対応漏れを防止する。",
            "lanes": [
                {"id": "user", "label": "利用部門"},
                {"id": "ops", "label": "運用担当"},
                {"id": "network", "label": "NW担当"},
                {"id": "carrier", "label": "回線事業者"},
            ],
            "stages": [
                {"id": "detect", "label": "検知・申告"},
                {"id": "verify", "label": "確認・切り分け"},
                {"id": "recover", "label": "対応・復旧"},
                {"id": "close", "label": "確認・完了"},
            ],
            "steps": [
                {"id": "report", "name": "障害申告", "lane": "user", "stage": "detect", "number": 1},
                {"id": "triage", "name": "一次確認", "lane": "ops", "stage": "detect", "number": 2},
                {"id": "monitor", "name": "監視確認", "lane": "ops", "stage": "verify", "number": 3},
                {"id": "device", "name": "機器確認", "lane": "network", "stage": "verify", "number": 4},
                {"id": "isolate", "name": "回線切り分け", "lane": "network", "stage": "verify", "number": 5},
                {"id": "escalate", "name": "エスカレーション", "lane": "ops", "stage": "verify", "number": 6},
                {"id": "provider", "name": "機器・回線調査／復旧対応", "lane": "carrier",
                 "stage": "recover", "style": "accent", "number": None},
                {"id": "recover", "name": "復旧作業", "lane": "ops", "stage": "recover", "number": 7},
                {"id": "notify", "name": "利用者連絡", "lane": "user", "stage": "close", "number": 8},
                {"id": "result", "name": "結果確認", "lane": "ops", "stage": "recover", "number": 9},
                {"id": "close", "name": "クローズ", "lane": "user", "stage": "close", "number": 10},
            ],
            "edges": [
                {"from": "report", "to": "triage"},
                {"from": "triage", "to": "monitor"},
                {"from": "triage", "to": "device"},
                {"from": "monitor", "to": "escalate"},
                {"from": "device", "to": "isolate"},
                {"from": "escalate", "to": "isolate"},
                {"from": "isolate", "to": "provider"},
                {"from": "provider", "to": "recover"},
                {"from": "recover", "to": "result"},
                {"from": "result", "to": "notify"},
                {"from": "notify", "to": "close"},
            ],
        },
        {
            "type": "message_sequence",
            "kicker": "変更作業シーケンス",
            "title": "関係者・機器・確認ポイントを、実行順に整理する",
            "lead": "メッセージの順序と送受信者を分けて確認し、作業前の認識差を減らす。",
            "participants": [
                {"id": "ops", "label": "運用担当"},
                {"id": "monitor", "label": "監視システム"},
                {"id": "branch", "label": "拠点ルータ"},
                {"id": "center", "label": "センタールータ"},
                {"id": "carrier", "label": "回線事業者"},
            ],
            "messages": [
                {"id": "detect", "from": "monitor", "to": "ops", "label": "障害検知"},
                {"id": "request", "from": "ops", "to": "branch", "label": "確認依頼"},
                {"id": "reply", "from": "branch", "to": "ops", "label": "疎通結果", "kind": "return"},
                {"id": "logs", "from": "monitor", "to": "branch", "label": "ログ確認"},
                {"id": "isolate", "from": "branch", "to": "center", "label": "区間切り分け"},
                {"id": "carrier", "from": "center", "to": "carrier", "label": "回線確認"},
                {"id": "recover", "from": "carrier", "to": "center", "label": "復旧連絡", "kind": "return"},
                {"id": "report", "from": "monitor", "to": "ops", "label": "正常性確認"},
            ],
            "phases": [
                {"label": "調査フェーズ", "from": "request", "to": "carrier"},
                {"label": "復旧フェーズ", "from": "recover", "to": "report"},
            ],
        },
    ],
}
